//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynUp_Desktop.model.pojo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Last
    {
        public int id { get; set; }
        public Nullable<int> id_employeelog { get; set; }
        public Nullable<int> id_teamlog { get; set; }
        public Nullable<int> id_tasklog { get; set; }
        public Nullable<int> id_teamhistorylog { get; set; }
        public Nullable<int> id_taskhistorylog { get; set; }
    }
}
